project_id = "oelmsmcgryeoryhonexw"

[functions.prioritizer]
verify_jwt = true

[functions.generate-task-explanation]
verify_jwt = true

[functions.ai-task-scorer]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.ai-training-chat]
verify_jwt = true

[functions.process-training-document]
verify_jwt = true

[functions.seed-client-knowledge]
verify_jwt = true

[functions.talent-search]
verify_jwt = true

[functions.import-professionals]
verify_jwt = true
